# Generated by Django 3.2.8 on 2021-10-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_auto_20211021_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='full_name',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='path',
            field=models.CharField(choices=[('fullstack', 'FullStack'), ('awsdevops', 'Aws&Devops'), ('datascience', 'DataScience')], max_length=20),
        ),
    ]
