# Generated by Django 3.2.8 on 2021-10-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0003_auto_20211022_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='path',
            field=models.CharField(choices=[('datascience', 'DataScience'), ('fullstack', 'FullStack'), ('awsdevops', 'Aws&Devops')], max_length=20),
        ),
    ]
